version: "3"
networks:
  develop:
    external:
      name: develop
services:
  mysql:
    image: daocloud.io/mysql:5.7
    container_name: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./conf/mysql/default.cnf:/etc/my.cnf
    networks:
      develop:
        ipv4_address: "192.19.0.3"
    ports:
      - "3306:3306"
  redis:
    image: redis:6.0.8
    container_name: "redis"
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    networks:
      develop:
        ipv4_address: "192.19.0.4"
  nginx:
    container_name: "nginx"
    image: nginx:1.7.9
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/conf:/etc/nginx/conf.d
      - ./conf/nginx/logs:/var/log/nginx
  php:
    container_name: "php"
    image: php:7.1.9-fpm-alpine
    expose: 
        - "9000"
  mongodb:
    image: "mongo:4.4.6"
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=123456
    networks:
      develop:
        ipv4_address: "192.19.0.5"
    ports:
      - "27017:27017"
  rabbitmq:
    image: "rabbitmq:3.7.9-management-alpine"
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
  etcd-node1:
    image: "bitnami/etcd:3.3.9"
    container_name: "etcd-node1"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes # 允许不用密码登录
      - ETCD_NAME=etcd-node1 # etcd 的名字
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node1:2380 # 列出这个成员的伙伴 URL 以便通告给集群的其他成员
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 # 用于监听伙伴通讯的URL列表
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 # 用于监听客户端通讯的URL列表
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node1:2379 # 列出这个成员的客户端URL，通告给集群中的其他成员
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster # 在启动期间用于 etcd 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER=etcd-node1=http://etcd-node1:2380,etcd-node2=http://etcd-node2:2380,etcd-node3=http://etcd-node3:2380 # 为启动初始化集群配置
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks:
      develop:
        ipv4_address: "192.19.0.6"
    expose:
      - "2380"
      - "2379"
    ports:
      - "23791:2379"
      - "23801:2380"
  etcd-node2:
    image: "bitnami/etcd:3.3.9"
    container_name: "etcd-node2"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes # 允许不用密码登录
      - ETCD_NAME=etcd-node2 # etcd 的名字
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node2:2380 # 列出这个成员的伙伴 URL 以便通告给集群的其他成员
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 # 用于监听伙伴通讯的URL列表
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 # 用于监听客户端通讯的URL列表
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node2:2379 # 列出这个成员的客户端URL，通告给集群中的其他成员
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster # 在启动期间用于 etcd 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER=etcd-node1=http://etcd-node1:2380,etcd-node2=http://etcd-node2:2380,etcd-node3=http://etcd-node3:2380 # 为启动初始化集群配置
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks:
      develop:
        ipv4_address: "192.19.0.7"
    expose:
      - "2380"
      - "2379"
    ports:
      - "23792:2379"
      - "23802:2380"
  etcd-node3:
    image: "bitnami/etcd:3.3.9"
    container_name: "etcd-node3"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes # 允许不用密码登录
      - ETCD_NAME=etcd-node3 # etcd 的名字
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node3:2380 # 列出这个成员的伙伴 URL 以便通告给集群的其他成员
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 # 用于监听伙伴通讯的URL列表
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 # 用于监听客户端通讯的URL列表
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node3:2379 # 列出这个成员的客户端URL，通告给集群中的其他成员
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster # 在启动期间用于 etcd 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER=etcd-node1=http://etcd-node1:2380,etcd-node2=http://etcd-node2:2380,etcd-node3=http://etcd-node3:2380 # 为启动初始化集群配置
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks:
      develop:
        ipv4_address: "192.19.0.8"
    expose:
      - "2380"
      - "2379"
    ports:
      - "23793:2379"
      - "23803:2380"
